<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>lOGIN</title>
</head>
<body>
    <div class="header">
    <h1>Login</h1>
    <form method="POST" action="logineval.php" >
    <label for="name"></label>
    <input type="text" name="name">
    <input type="password" name="password">
    <input type="submit" name="submit" value="login">
    </form>
    </div>
</body>
</html>